### ISSUE TITLE
Adds "Update TCA Profile" to every action group

### ISSUE THREAD

**Issue by KAmaia** [qfeys/ThrottleControlledAvionics#12]
It clutters up the default action groups with "Update TCA Profile".  

Linux/1.0.5/1.1.x

**Comment by allista** [comment]
The "update tca profile" action is there to allow TCA engine profile to adopt engine state changes caused by toggling an active group. I've searched KSP code for a better way (GameEvent or smth.) to catch group activation, but it seems there's none. The only other option I see is to leave this action for a user to assign to a specific action groups by hand when needed.

**Comment by allista** [comment]
What I've managed so far is this: TCA constantly scans the engines for assigned action groups and adds/removes itself to/from the same groups. Thus you don't see the "Update TCA Profile" action in editor, and in flight it is only present in the groups where some engines are toggled/enabled/disabled.

**Comment by allista** [comment]
Fixed in af9b7459f14113a7fdcc19705f2f732792b71206.
